### ISSUE TITLE
Can you have & not encoded to &amp; in url query strings and not have html entities decoded?

### ISSUE THREAD

**Issue by andynagai** [cheeriojs/cheerio#1132]
When the default decodeEntities: true I am seeing the & in url query strings being encoded as &amp; which is bad and the html entities not decoded which is good.

When decodeEntities: false I am seeing the & in url query strings left as is which is good and the html entities decoded which is not good.

The best case scenario for me is to not have any encoding done anywhere on the urls and to not decode html entities. Is this even possible using the load() method?

**Comment by andynagai** [comment]
Example of what I am seeing.

1) This will generate a invalid a url with &amp; in place of the & in between query string params and not decode html entities:

const $ = cheerio.load('<a href="www.domain.com/page?first=value&second=value">&#x3C;div&#x3E;content&#x3C;/div&#x3E;</a>');

This will output url like this:

www.yahoo.com/page?first=value&amp;second=value     // bad

The html entities will remain un-decoded. Which is good.

So when the default decodeEntities = true it will encode & in urls and not decode html entities?

2) When decodeEntities = false this will generate un-encoded & in urls and decoded html entities.

const $ = cheerio.load('<a href="www.domain.com/page?first=value&second=value">&#x3C;div&#x3E;content&#x3C;/div&#x3E;</a>', {decodeEntities: false});

Why are html entities decoded when decodeEntities=false ?

**Comment by 7iomka** [comment]
Same issue with cyrillic!
With {decodeEntities: false} i have decoded html-objects!!!! http://s1.micp.ru/Pe2b3.png
With {decodeEntities: true} i have normal html-objects, but cyrillic symbols looks like abracadabra!!! http://s2.micp.ru/8593R.png
I need urgent help! Thanks!

**Comment by ondrejrohon** [comment]
this is huge issue for me :/ any possible workaround adds more work than I'm actually trying to solve using cheerio

**Comment by bard** [comment]
I posted a workaround at https://github.com/cheeriojs/cheerio/issues/1198#issuecomment-481589878.

**Comment by fb55** [comment]
This should be resolved with the latest release.

**Comment by matthewgovaere** [comment]
I think this issue still exists.

An example here (shown within the console): https://codesandbox.io/s/cheerio-test-forked-0zxcj?file=/src/index.js
