### ISSUE TITLE
Can you make a new release.

### ISSUE THREAD

**Issue by 3ldar** [cheeriojs/cheerio#2774]
Hi,
I am currently using cheerio 1.0.0-rc12 and it was fine until one of other libraries we use forcing us to use `"moduleResolution" : "node16"` or newer. ('nodenext'). When we change this setting in tsconfig we started to have this error :
```
node_modules/cheerio/lib/esm/static.d.ts:2:42 - error TS2307: Cannot find module '.' or its corresponding type declarations.

2 import type { CheerioAPI, Cheerio } from '.';
                                           ~~~
```
It is possible to fix it by setting `skipLibCheck` to false or manually editing the d.ts file and replace `'.'` with `./index.js`. I can see it is already fixed in your source file. So can you please make a new release to reflect that fix?

**Comment by meriturva** [comment]
Also here we are waiting for the final version with ESM Module support.
Any ETA?

Thanks.
Diego

**Comment by tobiasmuehl** [comment]
> It is possible to fix it by setting skipLibCheck to false

needs to be set to `true`

**Comment by michaelfaith** [comment]
Would really appreciate a new release.  From the bit that I've used it, the library is a great step forward.  But we definitely need it to work with esm

**Comment by virtuallyunknown** [comment]
I am facing the same issue working in a monorepository using TypeScript `5.1.6` and cheerio `1.0.0-rc.12`. This kinda screws me up because I'm forced to use `skipLibCheck` even across packages that don't use `cheerio` or import anything from it, I am not exactly sure why.

Come on guys, it's 2023. Proper ESM support should be a thing for any library.

**Comment by benasher44** [comment]
I'm not sure how this "Can you make a new release." issue became the one about TypeScript NodeNext support, but it would be really great to see this supported for the next 1.0 release. Maybe a maintainer can rename this ticket, so it doesn't get overlooked? @fb55

**Comment by benasher44** [comment]
@fb55 would you be open to accepting a PR for a fix?

**Comment by benasher44** [comment]
Oh I see. It's because this issue was fixed already in #3251, but there hasn't been a release since then.

**Comment by niclimcy** [comment]
Will there be a new release anytime soon? Is anyone still maintaining this library?

**Comment by fb55** [comment]
Fixed with the [1.0 release](https://github.com/cheeriojs/cheerio/releases/tag/v1.0.0)!

**Comment by Rednas83** [comment]
I am just trying the library but I am still getting an errors when using typescript. In javascript I don't have issues.

**Tried**
* ![image](https://github.com/user-attachments/assets/dd91fca8-03de-4da5-9dae-d47cebca5e77)
* ![image](https://github.com/user-attachments/assets/2b8c8be1-d2fb-44b6-9156-b0e8064278cb)

**Comment by fb55** [comment]
The types package is not needed anymore and Cheerio ships its own types. Feel free to open another issue if you have issues with the types.

**Comment by mijhaels** [comment]
Why @crawlee/cheerio stills uses cheerio 1.0.0-rc12 from 3 years ago?
