### ISSUE TITLE
Element found despite it shouldn't be found.

### ISSUE THREAD

**Issue by SimonSchick** [cheeriojs/cheerio#806]
Have 2 test cases:

Browser is Version 48.0.2564.97 (64-bit), jQuery is: 2.2.0

``` javascript
'use strict';

var jq = document.createElement('script');
jq.src = "https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js";
document.getElementsByTagName('head')[0].appendChild(jq);
setTimeout(() =>
{
    const doc = $('body').replaceWith('<div id="testid"><div><div><b>Test</b></div></div>')
    const main = $('#testid');
    console.log($(main.find('div > div:contains("Test")').get(0)).html());
}, 2000);
```

This yields: `<b>Test</b>`

Node version is: 5.4.1
Cheerio version is: 0.19.0

``` javascript
'use strict';

const cheerio = require('cheerio');
const html = '<div id="testid"><div><div><b>Test</b></div></div>';
const $ = cheerio.load(html);
console.log($($('#testid').find('div > div:contains("Test")').get(0)).html());
console.log($($('#testid').find('div > div:contains("Test")').get(1)).html());
```

This yields: 

```
<div><b>Test</b></div>
<b>Test</b>
```

So for some reason cheerio matches the parent of the element that should be matched too.

**Comment by fb55** [comment]
Should be fixed with `cheerio@0.20.0`. Please let us now if that isn't the case, @SimonSchick.

**Comment by SimonSchick** [comment]
Nope, test case result is still wrong.
I still need to get(1) instead of 0.

**Comment by SimonSchick** [comment]
Old issue but still happening.

**Comment by fb55** [comment]
This seems to work as expected: All of the elements matched contain the string. The parent also contains it.
